### ISSUE TITLE
How to set the video width and height when capturing

### ISSUE THREAD

**Issue by adeelarshad83** [MathewSachin/ScreenWorks#3]
Hi

I want help to set the video width and height during capturing. How can I set that is there any property available

Regards

**Comment by MathewSachin** [comment]
You can see [Captura](https://GitHub.com/mathewsachin/Captura). 

It implements a StaticRegionProvider. Check it out. If you still need more help don't hesitate to ask

**Comment by adeelarshad83** [comment]
Hi

Thanks alot for your answer.

I have a desktop with resolution 1366 * 768 and the video I am capturing is
also of the same size but I want to make the video in either in 720*576 or
1920*1080

Regards

On Thu, Jan 14, 2016 at 3:34 PM, Mathew Sachin <notifications@github.com>
wrote:

> You can see Captura <https://GitHub.com/mathewsachin/Captura>.
>
> It implements a StaticRegionProvider. Check it out. If you still need more
> help don't hesitate to ask
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MathewSachin/ScreenWorks/issues/3#issuecomment-171602633>
> .
>



-- 
Regards
Adeel Arshad
Software Engineer
Pakistan Television Corporation Limited

**Comment by MathewSachin** [comment]
Do you mind cropping of the image while resizing. Some parts may be lost if you want to change to a different aspect ratio

**Comment by adeelarshad83** [comment]
Hi

I am playing the capture video on a decklink card and it did not allow this
aspect ratio so I have to change it accordingly and I can not crop as I
have to show whole desktop

Regards

On Thu, Jan 14, 2016 at 3:46 PM, Mathew Sachin <notifications@github.com>
wrote:

> Do you mind cropping of the image while resizing. Some parts may be lost
> if you want to change to a different aspect ratio
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MathewSachin/ScreenWorks/issues/3#issuecomment-171609842>
> .
>



-- 
Regards
Adeel Arshad
Software Engineer
Pakistan Television Corporation Limited

**Comment by MathewSachin** [comment]
Ok. If you could wait a bit. 
I would prepare a IImageProvider just for you

**Comment by adeelarshad83** [comment]
It will be really helpful

On Thu, Jan 14, 2016 at 3:58 PM, Mathew Sachin <notifications@github.com>
wrote:

> Ok. If you could wait a bit.
> I would prepare a IImageProvider just for you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MathewSachin/ScreenWorks/issues/3#issuecomment-171612816>
> .
>



-- 
Regards
Adeel Arshad
Software Engineer
Pakistan Television Corporation Limited

**Comment by MathewSachin** [comment]
I hope this would help.  
Sorry, I haven't tested the code.  

```csharp
using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;

namespace ScreenWorks
{
    public class ResizedWindowProvider : IImageProvider
    {
        int TargetWidth, TargetHeight;
        float ResizeWidth, ResizeHeight;

        Rectangle Rect;

        Func<bool> IncludeCursor;
        Color BackgroundColor;
        MouseKeyHook MouseKeyHookFacade = null;

        public ResizedWindowProvider(int TargetWidth, int TargetHeight, Func<bool> IncludeCursor, bool CaptureMouseClicks, bool CaptureKeyStrokes, Color BackgroundColor)
        {
            this.IncludeCursor = IncludeCursor;

            if (CaptureMouseClicks || CaptureKeyStrokes)
                MouseKeyHookFacade = new MouseKeyHook(CaptureMouseClicks, CaptureKeyStrokes);

            this.BackgroundColor = BackgroundColor;

            this.TargetHeight = TargetHeight;
            this.TargetWidth = TargetWidth;

            Rect = WindowProvider.DesktopRectangle;

            // Resize
            float RatioX = (float)TargetWidth / (float)Rect.Width,
                RatioY = (float)TargetHeight / (float)Rect.Height;

            float Ratio = Math.Min(RatioX, RatioY);

            ResizeWidth = Rect.Width * Ratio;
            ResizeHeight = Rect.Height * Ratio;
        }

        public Bitmap Capture()
        {
            bool IsCursor = IncludeCursor();

            var BMP = new Bitmap(Rect.Width, Rect.Height);

            using (var g = Graphics.FromImage(BMP))
            {
                g.CopyFromScreen(Rect.Location, Rect.Location,
                    new Size(Rect.Width, Rect.Height),
                    CopyPixelOperation.SourceCopy);

                if (IsCursor) g.DrawCursor();

                if (MouseKeyHookFacade != null) MouseKeyHookFacade.Draw(g);

                g.Flush();
            }

            var ResizedBMP = new Bitmap(TargetWidth, TargetHeight);

            using (var g = Graphics.FromImage(ResizedBMP))
            {
                g.CompositingQuality = CompositingQuality.HighQuality;
                g.InterpolationMode = InterpolationMode.HighQualityBicubic;
                g.SmoothingMode = SmoothingMode.HighQuality;

                if (BackgroundColor != Color.Transparent)
                    g.FillRectangle(new SolidBrush(BackgroundColor), 0, 0, TargetWidth, TargetHeight);

                g.DrawImage(BMP, 0, 0, ResizeWidth, ResizeHeight);
            }

            return ResizedBMP;
        }

        public int Height { get { return TargetHeight; } }

        public int Width { get { return TargetWidth; } }

        public int BufferSize { get { return TargetWidth * TargetHeight * 4; } }

        public void Dispose() { if (MouseKeyHookFacade != null) MouseKeyHookFacade.Dispose(); }

        public PixelFormat PixelFormat { get { return PixelFormat.Format32bppRgb; } }
    }
}
```

**Comment by MathewSachin** [comment]
NOTE: The part left out due to not matching of Aspect Ratio is filled with the BackgroundColor

**Comment by adeelarshad83** [comment]
Thank you so much.

**Comment by MathewSachin** [comment]
Welcome. Would add this class to the project source.

Well, thanks for pointing out the feature.

**Comment by MathewSachin** [comment]
Added a generalized ResizedImageProvider to [Screna](https://github.com/MathewSachin/Screna)
